name: Deploy nodejs app to heroku

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          yarn install
          yarn run build
          yarn run test
          
      - uses: thaithuytb/bunbu_deploy_ci_cd@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: github-action-auto-deploy
          heroku_email: ngoquangthai29112001@gmail.com
        
        
        
        
        
        
        
        
        
        
        
      
          
