name: Deploy nodejs app to heroku

on:
  push:
      branches: ['master']
  pull_request:
      branches: ['master']
  workflow_dispatch:
  
jobs:
  test-say-hello:
      runs-on: ubuntu-latest
      
      steps: 
        - run: echo Hello
  run-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: npm install
        - uses: ArtiomTr/jest-coverage-report-action@v2
  deploy-to-heroku:
      runs-on: ubuntu-latest
      steps:
        - uses: thaithuytb/bunbu_deploy_ci_cd@master
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: github-action-auto-deploy
            heroku_email: ngoquangthai29112001@gmail.com
    # build:
    #   runs-on: ubuntu-latest

    #   strategy:
    #     matrix:
    #       node-version: [16.x]

    #   steps:
    #     - uses: actions/checkout@master
    #     - name: Use Node.js ${{ matrix.node-version }}
    #       uses: actions/setup-node@v2
    #       with:
    #         node-version: ${{ matrix.node-version }}

    #     - name: Run a multi-line script
    #       run: |
    #         yarn install
    #         yarn run build
    #         yarn run test

    #     - uses: thaithuytb/bunbu_deploy_ci_cd@master
    #       with:
    #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
    #         heroku_app_name: github-action-auto-deploy
    #         heroku_email: ngoquangthai29112001@gmail.com

